---
# I might need to make a separate ansible-role for this

## https://github.com/Neilpang/acme.sh/wiki/Install-preparations
- name: Install curl, cron and socat (for standalone mode)
  package:
    name: "{{item}}"
    state: present
  with_items:
    - curl
    - "{{_unbound.cron | default('openssl')}}"
    - socat # netcat-openbsd (?), socat
  when: ansible_os_family != 'freeBSD'

- name: Install curl - FreeBSD
  package:
    name: curl
    state: present
  when: ansible_os_family == 'FreeBSD'

- name: Install socat from port (for standalone mode) - FreeBSD
  portinstall:
    name: socat
    state: present
  when: ansible_os_family == 'FreeBSD'

# Todo maybe ansiblefy this
- name: Get acme.sh for Let's Encrypt
  shell: curl https://get.acme.sh | sh
  args:
    executable: /bin/sh
    creates: /root/.acme.sh/acme.sh

- name: Copy account.conf settings
  template:
    src: account.conf
    dest: /root/.acme.sh/account.conf
  no_log: True

# I know it's not ideal but it works
- name: Force option
  file:
    path: "{{unbound.server.directory}}/{{unbound.server.ssl_service_pem}}"
    state: absent
  when: unbound_tls_acme_force

- name: Read variables and construct commands
  set_fact:
    unbound_tls_acme_ecc: "{% if unbound_tls_acme_ecc %} --ecc{% else %} {% endif %}"
    unbound_tls_acme_staging: "{% if unbound_tls_acme_staging %} --staging{% else %} {% endif %}"
    unbound_tls_acme_force: "{% if unbound_tls_acme_force %} --force{% else %} {% endif %}"
    unbound_tls_acme_debug: "{% if unbound_tls_acme_debug %} --debug{% else %} {% endif %}"

- name: Issue Certificate
  shell: >
    /root/.acme.sh/acme.sh --issue{{unbound_tls_acme_staging}}{{unbound_tls_acme_force}}{{unbound_tls_acme_debug}}{{unbound_tls_acme_ecc}}
    --domain {{unbound_tls_domain}}
    --server {{unbound_tls_acme_ca|default('https://acme-v01.api.letsencrypt.org/directory', true)}}
    --{{unbound_tls_acme_mode|default('standalone', true)}}
    --keylength {{unbound_tls_acme_keysize|default('2048', true)}}
    --key-file {{unbound.server.directory}}/{{unbound.server.ssl_service_key}}
    --fullchain-file {{unbound.server.directory}}/{{unbound.server.ssl_service_pem}}
    --reloadcmd '{{_unbound.reloadcmd}}' {{unbound_tls_acme_custom}}
  args:
    executable: /bin/sh
    creates: "{{unbound.server.directory}}/{{unbound.server.ssl_service_pem}}"

# you can check with `crontab -l`. `crontab -e` to edit (fish: set -xU EDITOR nano)
- name: Setup cron job (run every-7-days)
  cron:
    name: "acme.sh - Renew Certificate"
    job: "\"/root/.acme.sh\"/acme.sh --cron --home \"/root/.acme.sh\" > /dev/null"
    # https://crontab.guru/every-7-days
    minute: 18 # Don't run on the full hour mark to spread out load.
    hour: 0 # Midnight
    weekday: 0 # Sunday
