---
- name: Generate an OpenSSL private 4096 bits RSA key and certificate
  shell: |
    openssl req -x509 -newkey rsa:4096 -sha256 -nodes \
      -keyout {{unbound.server.directory}}/{{unbound.server.ssl_service_key}} \
      -out {{unbound.server.directory}}/{{unbound.server.ssl_service_pem}} \
      -subj '/CN={{unbound_tls_domain}}' -days 99990
  args:
    chdir: "{{unbound.server.directory}}"
    creates: "{{unbound.server.directory}}/{{unbound.server.ssl_service_pem}}"
